### ISSUE TITLE
Errors during plugin compile to 4.25 attempt

### ISSUE THREAD

**Issue by Hunanbean** [fblah/AnimNode#2]
Hello and thank you again for this project (commented on youtube)
I am attempting to compile the plugin for engine version 4.25 
this is the first time i have tried to compile a plugin to try to update it.
my programing knowledge is 0, so this is most probably my user error.
here are the errors that are reported to me

`ParallelExecutor.ExecuteActions:   [5/13] Module.AnimNodeEditor.cpp
ParallelExecutor.ExecuteActions:   O:\animnode425\HostProject\Plugins\animnode\Source\AnimNodeEditor\AnimNodeEditor.h(10): fatal error C1083: Cannot open include file: 'ModuleManager.h': No such file or directory
ParallelExecutor.ExecuteActions:   [6/13] Module.AnimNodeEditor.gen.cpp
ParallelExecutor.ExecuteActions:   C:\UE\UE_4.25\Engine\Source\AnimNode\Public\AnimationMirrorData.h(10): fatal error C1083: Cannot open include file: 'Object.h': No such file or directory
ParallelExecutor.ExecuteActions:   [7/13] Module.AnimNode.gen.cpp
ParallelExecutor.ExecuteActions:   C:\UE\UE_4.25\Engine\Source\AnimNode/Public/AnimationMirrorData.h(10): fatal error C1083: Cannot open include file: 'Object.h': No such file or directory
ParallelExecutor.ExecuteActions:   [8/13] Module.AnimNode.cpp
ParallelExecutor.ExecuteActions:   O:\animnode425\HostProject\Plugins\animnode\Source\AnimNode\AnimNode.h(10): fatal error C1083: Cannot open include file: 'ModuleManager.h': No such file or directory
UnrealBuildTool.Main: CompilationResultException: Error: OtherCompilationError
UnrealBuildTool.Main:    at UnrealBuildTool.ActionGraph.ExecuteActions(BuildConfiguration BuildConfiguration, List`1 ActionsToExecute) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\System\ActionGraph.cs:line 242
UnrealBuildTool.Main:    at UnrealBuildTool.BuildMode.Build(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 372
UnrealBuildTool.Main:    at UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 219
UnrealBuildTool.Main:    at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 550`

Thank you, and be well!

**Comment by fblah** [comment]
I have updated the plugin to 4.25. Please try it out and let me know. Close this issue once you have confirmed it works on your end.

**Comment by Hunanbean** [comment]
Thank you for doing that, it seems to be working!
closing ticket
Be well!
