### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Avatarus-one** [fblah/AnimNode#3]
I'm unable to package the project with the plugin enabled.

Log:

> PackagingResults: Warning: Referenced directory 'C:\Epic Games\UE_4.25\Engine\Source\AnimNode\Public' does not exist.
PackagingResults: Warning: Referenced directory 'C:\Epic Games\UE_4.25\Engine\Source\AnimNodeEditor\Public' does not exist.
**UATHelper: Packaging (Windows (64-bit)):   ERROR: Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.**

The plugin was added to `<project_name>/Plugins/AnimNode/` for all developers to have access to it. Could this be the reason of the build problem? Or it's because UnrealEd is listed in `AnimNodeEditor.Build.cs`?

UPD: It happens on development builds only, shipping has no errors.

**Comment by fblah** [comment]
I have made an update, can you tell me if it fixes the issue?

**Comment by Avatarus-one** [comment]
Yes, the error is gone, thanks a lot.

**Comment by fblah** [comment]
Don't forget to close the issue :)
